apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: flask
 template:
  metadata:
   labels:
    app: flask
  spec:
   containers:
    - name: backend
      image: mahmoodabuawwad/backend
      imagePullPolicy: Always
      env:
      - name: HOST
        value: "192.168.205.155"
      - name: PORT  # desired in flask-service.yaml
        value: "30000"

      ports:
       - containerPort: 5000
