apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: flask
 template:
  metadata:
   labels:
    app: flask
  spec:
   containers:
    - name: backend
      image: mahmoodabuawwad/backend
      imagePullPolicy: Always
      env:
      - name: HOST
        valueFrom:
         configMapKeyRef:
          name: flask-config
          key: HOST
      - name: PORT
        valueFrom:
         configMapKeyRef:
          name: flask-config
          key: PORT

      ports:
       - containerPort: 5000
