apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: flask
  name: backend-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30007
