apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql-pod
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
    - name: database
      image: mysql
      env:
      - name: MYSQL_DATABASE
        value: "backend"
      - name: MYSQL_ROOT_PASSWORD
        value: "flask"
      - name: MYSQL_PASSWORD
        value: "flask"
      - name: MYSQL_USER
        value: "flask"
      imagePullPolicy: Always
      ports:
       - containerPort: 3306
   volumes:
    - name: test-volume
      hostPath:
       path: /var/opt/.
       type: Directory
