apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql-pod
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
    - name: database
      image: mysql
      env:
      - name: MYSQL_DATABASE
        valueFrom:
         configMapKeyRef:
          name: mysql-config
          key: MYSQL_DATABASE
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:           
         configMapKeyRef:
          name: mysql-config
          key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_PASSWORD
        valueFrom:           
         configMapKeyRef:
          name: mysql-config
          key: MYSQL_PASSWORD
      - name: MYSQL_USER
        valueFrom:           
         configMapKeyRef:
          name: mysql-config
          key: MYSQL_USER
     
      imagePullPolicy: Always
      ports:
       - containerPort: 3306
   volumes:
    - name: test-volume
      hostPath:
       path: /var/opt/.
